const productos = [
    {
        nombre: "Grafica RTX 4080",
        id: 1,
        descripcion: "Tarjeta grafica gama media-alta",
        precio: 500,
        cantidad: 1,
        img: './images/video-geforce-rtx-4080-16gb-msi-gaming-x-trio-0.jpg',
    },
    {
        nombre: "Pc Gamer Prearmada",
        id: 2,
        descripcion: "Pc armada pensada para las necesidades de juegos actuales",
        precio: 1000,
        cantidad: 1,
        img: './images/pc_amd-7401-b81b0560b78bd447e316373419933297-640-0.png',
    },
    {
        nombre: "Combo Perifericos Hyper X",
        id: 3,
        descripcion: "Kit de perifericos gamer primera marca",
        precio: 250,
        cantidad: 1,
        img: './images/1019-producto-combo-hyperx-1321.jpg',
    },
    {
        nombre: "CPU Watercooling MSI",
        id: 4,
        descripcion: "Sistema de refrigeracion liquida MSI",
        precio: 500,
        cantidad: 1,
        img: './images/imagen.jpg',
    },
    {
        nombre: "CPU Intel I9 9900k",
        id: 5,
        descripcion: "Procesador 8 nucleos, Velocidad de reloj 3.6 GHz",
        precio: 800,
        cantidad: 1,
        img: './images/s-l1200.jpg',
    },
    {
        nombre: "Modulo RAM KINGSTON 16GB RGB",
        id: 6,
        descripcion: "Memoria ram kingston 3200mhz",
        precio: 200,
        cantidad: 1,
        img: './images/88f86d09-ad01-434c-8084-50547eb5e83b.ca6fade901fb02d0688b3239f4a13794.webp',
    },

];